twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 10
      behaviors:
        topic: cmd_vel_behaviors
        timeout: 0.5
        priority: 20
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 100
    use_sim_time: true
